# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pl20_design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        """
        function creates the GUI
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(734, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTarget = QtWidgets.QLabel(self.centralwidget)
        self.labelTarget.setObjectName("labelTarget")
        self.verticalLayout.addWidget(self.labelTarget)
        self.target = QtWidgets.QLineEdit(self.centralwidget)
        self.target.setAcceptDrops(False)
        self.target.setObjectName("target")
        self.verticalLayout.addWidget(self.target)
        self.labelInput = QtWidgets.QLabel(self.centralwidget)
        self.labelInput.setObjectName("labelInput")
        self.verticalLayout.addWidget(self.labelInput)
        self.input = QtWidgets.QTextEdit(self.centralwidget)
        self.input.setAutoFillBackground(False)
        self.input.setReadOnly(False)
        self.input.setObjectName("input")
        self.verticalLayout.addWidget(self.input)
        self.labelProtocol = QtWidgets.QLabel(self.centralwidget)
        self.labelProtocol.setObjectName("labelProtocol")
        self.verticalLayout.addWidget(self.labelProtocol)
        self.protocol = QtWidgets.QTextEdit(self.centralwidget)
        self.protocol.setAcceptDrops(False)
        self.protocol.setReadOnly(True)
        self.protocol.setPlaceholderText("")
        self.protocol.setObjectName("protocol")
        self.verticalLayout.addWidget(self.protocol)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelOutput = QtWidgets.QLabel(self.centralwidget)
        self.labelOutput.setObjectName("labelOutput")
        self.verticalLayout_2.addWidget(self.labelOutput)
        self.output = QtWidgets.QTextEdit(self.centralwidget)
        self.output.setAcceptDrops(False)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout_2.addWidget(self.output)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fileTwo = QtWidgets.QCheckBox(self.centralwidget)
        self.fileTwo.setObjectName("fileTwo")
        self.verticalLayout_4.addWidget(self.fileTwo)
        self.fileOne = QtWidgets.QCheckBox(self.centralwidget)
        self.fileOne.setObjectName("fileOne")
        self.verticalLayout_4.addWidget(self.fileOne)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.compareList = QtWidgets.QPushButton(self.centralwidget)
        self.compareList.setToolTipDuration(1)
        self.compareList.setObjectName("compareList")
        self.verticalLayout_3.addWidget(self.compareList)
        self.compareSub = QtWidgets.QPushButton(self.centralwidget)
        self.compareSub.setObjectName("compareSub")
        self.verticalLayout_3.addWidget(self.compareSub)
        self.compareCel = QtWidgets.QPushButton(self.centralwidget)
        self.compareCel.setObjectName("compareCel")
        self.verticalLayout_3.addWidget(self.compareCel)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 734, 22))
        self.menubar.setObjectName("menubar")
        self.menuMen = QtWidgets.QMenu(self.menubar)
        self.menuMen.setObjectName("menuMen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuMen.addAction(self.actionClose)
        self.menuMen.addAction(self.actionHelp)
        self.menubar.addAction(self.menuMen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PLD20"))
        self.labelTarget.setText(_translate("MainWindow", "Target"))
        self.target.setPlaceholderText(_translate("MainWindow", "Insert target here"))
        self.labelInput.setText(_translate("MainWindow", "Input"))
        self.input.setPlaceholderText(_translate("MainWindow", "Insert list of words or file here"))
        self.labelProtocol.setText(_translate("MainWindow", "Protocol"))
        self.labelOutput.setText(_translate("MainWindow", "Output"))
        self.fileTwo.setText(_translate("MainWindow", "File (two columns)"))
        self.fileOne.setText(_translate("MainWindow", "File (one column)"))
        self.compareList.setToolTip(_translate("MainWindow", "Click here to compare your target with a list of words"))
        self.compareList.setText(_translate("MainWindow", "Compare with list/file"))
        self.compareSub.setToolTip(_translate("MainWindow", "Click here to compare your word with SUBTLEX"))
        self.compareSub.setText(_translate("MainWindow", "Compare with SUBTLEX"))
        self.compareCel.setToolTip(_translate("MainWindow", "Click here to compare your word with CELEX"))
        self.compareCel.setText(_translate("MainWindow", "Compare with database"))
        self.menuMen.setTitle(_translate("MainWindow", "File"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
